import 'destyle.css';
import '@/styles/global.scss';
import { StyledComponentsRegistry } from '@/app/styling/StyledComponentsRegistry';

export const metadata = {
  title: 'next-view-transition',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <StyledComponentsRegistry>{ children }</StyledComponentsRegistry>
      </body>
    </html>
  )
}
