import 'destyle.css';
import '@/styles/global.scss';
import { StyledComponentsRegistry } from '@/app/styling/StyledComponentsRegistry';

export const metadata = {
  title: 'next-view-transitions-api',
  description: 'Generated by create next app',
  openGraph: {
    title: 'next-view-transitions-api',
    description: 'Generated by create next app',
    utl: 'https://next-view-transitions-api.netlify.app/',
    siteName: 'next-view-transitions-api',
    images: [{
      url: 'https://next-view-transitions-api.netlify.app/images/counterattack-of-the-timer.jpg',
      width: 1200,
      height: 630
    }],
    local: 'ja_JP',
    type: 'website',
    authors: ['君塚史高']
  },
  twitter: {
    card: 'summary_large_image',
    images: ['https://next-view-transitions-api.netlify.app/images/counterattack-of-the-timer.jpg'],
    creator: '@ki_230'
  }
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ja">
      <body>
        <StyledComponentsRegistry>{ children }</StyledComponentsRegistry>
      </body>
    </html>
  )
}
